-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 18:14:55 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `idlivro` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(250) NOT NULL,
  `Isbn` INT NOT NULL,
  `Status` TINYTEXT NOT NULL,
  `Exemplar` INT NULL,
  PRIMARY KEY (`idlivro`),
  UNIQUE INDEX `idlivro_UNIQUE` (`idlivro` ASC) VISIBLE,
  UNIQUE INDEX `livrocol_UNIQUE` (`Titulo` ASC) VISIBLE,
  UNIQUE INDEX `livrocol1_UNIQUE` (`Isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuário` (
  `idusuário` INT NOT NULL AUTO_INCREMENT,
  `Nomeusuário` VARCHAR(150) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Emprestimo` TINYTEXT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  PRIMARY KEY (`idusuário`),
  UNIQUE INDEX `idusuário_UNIQUE` (`idusuário` ASC) VISIBLE,
  INDEX `fk_usuário_livro_idx` (`livro_idlivro` ASC) VISIBLE,
  CONSTRAINT `fk_usuário_livro`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `mydb`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
